"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VvtSpV6RAMl
 */
import { Avatar, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { CardHeader, CardContent, Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import Image from "next/image";
import { useState } from "react";
import { useChat, type Message } from "ai/react";
import { useLocalStorage } from "@/lib/hooks/use-local-storage";
import { ChatList } from "./ChatList";
import { nanoid } from "nanoid";
import { IconOpenAI } from "./icons";

export function Chat() {
  const [isChatOpen, setIsChatOpen] = useState(false);

  const {
    messages,
    append,
    reload,
    stop,
    isLoading,
    input,
    setInput,
    handleInputChange,
    handleSubmit,
  } = useChat();

  function toggleChat() {
    setIsChatOpen((prev) => !prev);
  }

  return (
    <div className="">
      {!isChatOpen ? (
        <div
          onClick={toggleChat}
          className="fixed bottom-4 right-4 cursor-pointer shadow-xl rounded-full p-2 bg-purple-gradient"
        >
          <Image
            src="/assets/icons/chat.svg"
            alt="image"
            width={24}
            height={24}
          />
        </div>
      ) : (
        <>
          <Card className="fixed bottom-4 right-4 w-full max-w-sm m-0 shadow-xl">
            <CardHeader className="rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <IconOpenAI />

                  <h3 className="text-sm font-bold">Chat with Alice</h3>
                </div>
                <Button size="sm" variant="ghost" onClick={toggleChat}>
                  <XIcon className="w-4 h-4" />
                  <span className="sr-only">Close</span>
                </Button>
              </div>
            </CardHeader>
            <CardContent className="p-0">
              <div className="flex flex-col gap-2 p-4 h-[200px] overflow-y-scroll">
                <div className="flex items-start gap-2">
                  <ChatList messages={messages} />
                </div>
              </div>
              <div className="border-t border-gray-200 dark:border-gray-700">
                <div>
                  <form onSubmit={handleSubmit} className="flex gap-1 p-2">
                    <div className="search">
                      <Input
                        placeholder="Type a message"
                        className="search-field  h-8"
                        value={input}
                        onChange={handleInputChange}
                      />
                    </div>
                    <Button
                      className="h-[50px] justify-center bg-purple-gradient"
                      type="submit"
                    >
                      <SendIcon className="w-4 h-4" />
                      <span className="sr-only">Send</span>
                    </Button>
                  </form>
                </div>
              </div>
            </CardContent>
          </Card>
        </>
      )}
    </div>
  );
}

function XIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}

function SendIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="#fff"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  );
}
